[package]
name = "zint-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
image = "0.24.6"
blake3 = "1.4.1"
libc = "0.2.147"

[build-dependencies]
bindgen = "0.66"
